# Generated by Django 5.2 on 2025-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("servingSize", models.FloatField()),
                ("caloriesPerServing", models.FloatField()),
                ("proteinContent", models.FloatField()),
                ("fatContent", models.FloatField()),
                ("carbohydrateContent", models.FloatField()),
                ("allergens", models.JSONField(default=list)),
                ("dietaryOptions", models.JSONField(default=list)),
                ("nutritionScore", models.FloatField()),
                ("imageUrl", models.URLField(blank=True)),
            ],
        ),
    ]
