# Generated by Django 5.2.7 on 2025-11-23 17:35

from django.db import migrations


def backfill_micronutrient_targets(apps, schema_editor):
    """
    Backfill micronutrient targets for existing NutritionTargets records.
    Only updates targets that:
    1. Have empty or missing micronutrients field
    2. Are not custom (is_custom=False)
    3. Have associated user metrics
    """
    NutritionTargets = apps.get_model('accounts', 'NutritionTargets')
    UserMetrics = apps.get_model('accounts', 'UserMetrics')
    
    # Import the function (using the actual module path)
    import sys
    import os
    # Add project root to path if needed
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if project_root not in sys.path:
        sys.path.insert(0, project_root)
    
    from project.utils.nutrition_calculator import calculate_micronutrient_targets
    
    # Find all nutrition targets that need updating
    targets_to_update = NutritionTargets.objects.filter(
        is_custom=False
    ).select_related('user')
    
    updated_count = 0
    skipped_count = 0
    
    for target in targets_to_update:
        # Check if micronutrients is empty or missing
        if not target.micronutrients or target.micronutrients == {}:
            try:
                # Try to get user metrics
                metrics = UserMetrics.objects.get(user=target.user)
                
                # Calculate micronutrient targets
                micronutrient_targets = calculate_micronutrient_targets(
                    metrics.age,
                    metrics.gender
                )
                
                # Update the target
                target.micronutrients = micronutrient_targets
                target.save(update_fields=['micronutrients'])
                updated_count += 1
            except UserMetrics.DoesNotExist:
                # User doesn't have metrics, skip
                skipped_count += 1
                continue
            except Exception as e:
                # Log error but continue
                print(f"Error updating targets for user {target.user.id}: {e}")
                skipped_count += 1
                continue
    
    print(f"Migration completed: {updated_count} targets updated, {skipped_count} skipped")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Clear micronutrient targets (set to empty dict).
    """
    NutritionTargets = apps.get_model('accounts', 'NutritionTargets')
    
    # Clear micronutrients for non-custom targets
    NutritionTargets.objects.filter(is_custom=False).update(micronutrients={})


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_nutritiontargets_usermetrics"),
    ]

    operations = [
        migrations.RunPython(
            backfill_micronutrient_targets,
            reverse_code=reverse_migration
        ),
    ]
