# Generated by Django 5.2.8 on 2025-12-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_backfill_micronutrient_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(help_text='Username or ID of the deleted user', max_length=150)),
                ('email', models.EmailField(help_text='Email of the deleted user (hashed or raw depending on policy)', max_length=254)),
                ('reason', models.TextField(blank=True, help_text='Reason for deletion if provided')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Summary of deleted/anonymized counts')),
            ],
        ),
    ]
