# Generated by Django 5.2.7 on 2025-10-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0005_update_food_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodentry",
            name="imageUrlHigh",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="imageUrlLow",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="imageUrlMedium",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="foodproposal",
            name="imageUrlHigh",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="foodproposal",
            name="imageUrlLow",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="foodproposal",
            name="imageUrlMedium",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
