# Generated by Django 5.2.7 on 2025-11-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0007_alter_foodproposal_isapproved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="foodentry",
            name="base_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="category_overridden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="category_overridden_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_price_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="category_override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="currency",
            field=models.CharField(default="TRY", max_length=3),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="price_category",
            field=models.CharField(
                blank=True,
                choices=[("₺", "₺"), ("₺ ₺", "₺ ₺"), ("₺ ₺₺", "₺ ₺₺")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="price_unit",
            field=models.CharField(
                choices=[("per_100g", "Per 100g"), ("per_unit", "Per Unit")],
                default="per_100g",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="foodproposal",
            name="base_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodproposal",
            name="currency",
            field=models.CharField(default="TRY", max_length=3),
        ),
        migrations.AddField(
            model_name="foodproposal",
            name="price_unit",
            field=models.CharField(
                choices=[("per_100g", "Per 100g"), ("per_unit", "Per Unit")],
                default="per_100g",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PriceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        choices=[("per_100g", "Per 100g"), ("per_unit", "Per Unit")],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                (
                    "old_base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "old_price_category",
                    models.CharField(
                        blank=True,
                        choices=[("₺", "₺"), ("₺ ₺", "₺ ₺"), ("₺ ₺₺", "₺ ₺₺")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "new_price_category",
                    models.CharField(
                        blank=True,
                        choices=[("₺", "₺"), ("₺ ₺", "₺ ₺"), ("₺ ₺₺", "₺ ₺₺")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("price_update", "Price Update"),
                            ("category_override", "Category Override"),
                            ("threshold_recalc", "Threshold Recalculation"),
                            ("recipe_recalc", "Recipe Recalculation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_audits",
                        to="foods.foodentry",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PriceCategoryThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        choices=[("per_100g", "Per 100g"), ("per_unit", "Per Unit")],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                (
                    "lower_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "upper_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_recalculated_at", models.DateTimeField(blank=True, null=True)),
                ("updates_since_recalculation", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Price category threshold",
                "verbose_name_plural": "Price category thresholds",
                "unique_together": {("price_unit", "currency")},
            },
        ),
        migrations.CreateModel(
            name="PriceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_reports",
                        to="foods.foodentry",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_price_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
