# Generated by Django 5.2 on 2025-11-22 12:00

from django.db import migrations
import os
import sys
from api.db_initialization.load_food_from_json import FoodLoader


def load_food_data(apps, schema_editor):
    """
    Load USDA FDC food data using the standalone FoodLoader script.
    """

    # Path to your JSON file
    json_path = os.path.join(
        os.path.dirname(__file__), "../../api/db_initialization/NewFoodDatabase.json"
    )

    if not os.path.exists(json_path):
        print(
            f"⚠️  JSON fil for FNDDS DB was not found at {json_path}, skipping data load"
        )
        return

    print(f"Running FoodLoader migration with file: {json_path}")

    # Create loader instance and load foods
    # Use skip_errors=True to continue even if some items fail
    loader = FoodLoader(skip_errors=True)

    try:
        # Load all foods from the JSON file
        loader.load_foods(json_path, limit=None)
        print(
            f"✓ Migration completed: {loader.count} foods loaded, {loader.failed} failed"
        )
    except Exception as e:
        print(f"❌ Migration failed: {e}")
        raise


def reverse_migration(apps, schema_editor):
    """
    Remove all food entries created by this migration.
    WARNING: This will delete ALL FoodEntry objects!
    """
    FoodEntry = apps.get_model("foods", "FoodEntry")
    Allergen = apps.get_model("foods", "Allergen")

    food_count = FoodEntry.objects.count()
    allergen_count = Allergen.objects.count()

    FoodEntry.objects.all().delete()
    Allergen.objects.all().delete()

    print(f"✓ Deleted {food_count} food entries and {allergen_count} allergens")


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0008_foodentry_micronutrients_foodproposal_micronutrients"),
    ]

    operations = [
        migrations.RunPython(load_food_data, reverse_migration),
    ]
