# Generated by Django 5.2 on 2025-11-22 12:00

from django.db import migrations
import os
import zipfile
from api.db_initialization.load_food_from_json import FoodLoader


def load_food_data(apps, schema_editor):
    """
    Load USDA FDC food data using the standalone FoodLoader script.
    Checks if JSON file is already unzipped, otherwise unzips the zip file.
    """

    # Path to the JSON file and zip file
    db_init_dir = os.path.join(os.path.dirname(__file__), "../../api/db_initialization")
    json_path = os.path.join(db_init_dir, "NewFoodDatabase.json")
    zip_path = os.path.join(db_init_dir, "NewFoodDatabase.json.zip")

    json_path = os.path.abspath(json_path)
    zip_path = os.path.abspath(zip_path)

    # Check if JSON file already exists (already unzipped)
    if os.path.exists(json_path):
        print(f"Found existing JSON file at: {json_path}")
        print("Using existing JSON file (already unzipped)")
    else:
        # JSON file doesn't exist, check for zip file and unzip it
        if not os.path.exists(zip_path):
            print(
                f"⚠️  Neither JSON file nor ZIP file found. "
                f"JSON: {json_path}, ZIP: {zip_path}. Skipping data load."
            )
            return

        print(f"JSON file not found, found ZIP file at: {zip_path}")
        print(f"Extracting ZIP file to: {os.path.dirname(json_path)}")

        # Extract the zip file to the same directory as the zip file
        try:
            with zipfile.ZipFile(zip_path, "r") as zip_ref:
                zip_ref.extractall(os.path.dirname(json_path))
        except zipfile.BadZipFile:
            raise ValueError(f"Invalid or corrupted ZIP file: {zip_path}")

        # Verify the JSON file was extracted
        if not os.path.exists(json_path):
            raise FileNotFoundError(
                f"ZIP file extracted but JSON file not found at: {json_path}"
            )

        print(f"✓ Successfully extracted JSON file: {json_path}")

    # Verify the JSON file exists and is readable
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"JSON file not found: {json_path}")

    # Get historical models - these will have the fields as they existed at this migration
    FoodEntry = apps.get_model('foods', 'FoodEntry')
    Allergen = apps.get_model('foods', 'Allergen')

    # Create loader instance with historical models and load foods
    # Use skip_errors=True to continue even if some items fail
    loader = FoodLoader(skip_errors=True, food_entry_model=FoodEntry, allergen_model=Allergen)

    try:
        # Load all foods from the JSON file
        loader.load_foods(json_path, limit=None)
        print(
            f"✓ Migration completed: {loader.count} foods loaded, {loader.failed} failed"
        )
    except Exception as e:
        print(f"❌ Migration failed: {e}")
        raise


def reverse_migration(apps, schema_editor):
    """
    Remove all food entries created by this migration.
    WARNING: This will delete ALL FoodEntry objects!
    """
    FoodEntry = apps.get_model("foods", "FoodEntry")
    Allergen = apps.get_model("foods", "Allergen")

    food_count = FoodEntry.objects.count()
    allergen_count = Allergen.objects.count()

    FoodEntry.objects.all().delete()
    Allergen.objects.all().delete()

    print(f"✓ Deleted {food_count} food entries and {allergen_count} allergens")


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0009_foodentry_base_price_and_more"),
    ]

    operations = [
        migrations.RunPython(load_food_data, reverse_migration),
    ]
