# Generated by Django 5.2.8 on 2025-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_load_FNDDS_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproposal',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, this rejected proposal is kept as a private food for the user'),
        ),
    ]
