# Generated by Django 5.2.8 on 2025-11-23 20:05

from django.db import migrations
import requests

def remove_broken_links(apps, schema_editor):
    FoodEntry = apps.get_model('foods', 'FoodEntry')
    # Filter for external images
    # We exclude empty ones, local ones, and static ones
    external_foods = FoodEntry.objects.exclude(imageUrl="").exclude(imageUrl__startswith="/media/").exclude(imageUrl__startswith="/static/")
    
    print(f"\nChecking {external_foods.count()} external links...")
    
    removed_count = 0
    # Iterate over a list to avoid issues with queryset modification during iteration
    for food in list(external_foods):
        try:
            # Use a short timeout to prevent hanging deployment
            response = requests.head(food.imageUrl, timeout=5, allow_redirects=True)
            if response.status_code != 200:
                print(f"Removing broken link: {food.imageUrl} (Status: {response.status_code})")
                food.imageUrl = ""
                food.save()
                removed_count += 1
        except Exception as e:
            print(f"Removing broken link: {food.imageUrl} (Error: {e})")
            food.imageUrl = ""
            food.save()
            removed_count += 1
            
    print(f"Removed {removed_count} broken links.")

def reverse_remove_broken_links(apps, schema_editor):
    # We cannot restore the deleted links, so this does nothing
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_foodproposal_is_private'),
    ]

    operations = [
        migrations.RunPython(remove_broken_links, reverse_remove_broken_links),
    ]
