# Generated by Django 5.2.8 on 2025-12-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0016_normalize_micronutrients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='micronutrients',
        ),
        migrations.AlterField(
            model_name='foodentrymicronutrient',
            name='food_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micronutrient_values', to='foods.foodentry'),
        ),
        migrations.AlterField(
            model_name='foodentrymicronutrient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodentrymicronutrient',
            name='micronutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='foods.micronutrient'),
        ),
        migrations.AlterField(
            model_name='micronutrient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
