# Generated by Django 5.2.7 on 2025-12-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0016_update_food_images"),
        ("foods", "0017_remove_foodentry_micronutrients_and_more"),
    ]

    operations = []
