# Generated by Django 5.2.8 on 2025-12-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_remove_foodentry_micronutrients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micronutrient',
            name='unit',
            field=models.CharField(default='g', max_length=2),
        ),
    ]
