# Generated by Django to merge conflicting migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0018_alter_micronutrient_unit"),
        ("foods", "0018_merge_20251209_1248"),
    ]

    operations = []
