# Generated by Django migration script on 2025-12-13
# Adds allergen tags to all existing food entries using the explicit mappings from allergen_mapping.json

from django.db import migrations
import json
import os


def add_allergen_tags(apps, schema_editor):
    """
    Add allergen tags to all existing food entries using the explicit mappings
    from allergen_mapping.json.
    """
    FoodEntry = apps.get_model("foods", "FoodEntry")
    Allergen = apps.get_model("foods", "Allergen")

    # Load allergen mappings from JSON file
    json_path = os.path.join(
        os.path.dirname(__file__), "docs/allergen_mapping.json"
    )
    
    with open(json_path, "r", encoding="utf-8") as f:
        mapping_data = json.load(f)
    
    allergen_types = mapping_data["allergen_types"]
    food_mappings = mapping_data["food_allergen_mappings"]
    
    # Create all allergen entries if they don't exist
    allergen_objects = {}
    for name in allergen_types:
        allergen, _ = Allergen.objects.get_or_create(name=name)
        allergen_objects[name] = allergen
    
    print(f"✓ Created/verified {len(allergen_objects)} allergen types: {allergen_types}")

    # Create a lookup dict for food allergen mappings
    food_allergen_map = {item["name"]: item["allergens"] for item in food_mappings}
    
    print(f"✓ Loaded allergen mappings for {len(food_allergen_map)} foods")

    # Process all foods
    total_foods = FoodEntry.objects.count()
    foods_updated = 0
    allergens_assigned = 0
    not_found = 0

    print(f"Processing {total_foods} foods...")

    for food in FoodEntry.objects.all().iterator():
        # Look up allergens for this food
        allergen_names = food_allergen_map.get(food.name, [])
        
        if allergen_names:
            allergen_objs = [allergen_objects[name] for name in allergen_names if name in allergen_objects]
            if allergen_objs:
                food.allergens.set(allergen_objs)
                foods_updated += 1
                allergens_assigned += len(allergen_objs)
        else:
            # Food not in mapping - clear any existing allergens
            food.allergens.clear()
            not_found += 1

    print(f"✓ Updated {foods_updated} foods with {allergens_assigned} allergen tags")
    print(f"✓ {not_found} foods had no allergen mappings (cleared)")


def reverse_migration(apps, schema_editor):
    """
    Remove allergen tags from all food entries (but keep allergen definitions).
    """
    FoodEntry = apps.get_model("foods", "FoodEntry")

    # Clear allergens from all foods
    count = 0
    for food in FoodEntry.objects.all().iterator():
        food.allergens.clear()
        count += 1

    print(f"✓ Removed all allergen tags from {count} foods")


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0018_merge_20251209_1248"),
    ]

    operations = [
        migrations.RunPython(add_allergen_tags, reverse_migration),
    ]
