# Generated by Django 5.2.8 on 2025-12-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0018_alter_micronutrient_unit'),
        ('foods', '0018_merge_20251209_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproposal',
            name='is_private',
        ),
    ]
