# Generated by Django 5.2.8 on 2025-12-11 21:27

from django.db import migrations, models

def set_validated_for_existing(apps, schema_editor):
    FoodEntry = apps.get_model('foods', 'FoodEntry')
    FoodEntry.objects.all().update(validated=True)


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0019_remove_foodproposal_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_validated_for_existing),
    ]
