# Generated by Django 5.2.8 on 2025-12-13 14:04

import django.db.models.deletion
from django.db import migrations, models


def delete_old_proposals(apps, schema_editor):
    """Delete all existing FoodProposals before refactoring."""
    FoodProposal = apps.get_model('foods', 'FoodProposal')
    FoodProposal.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0021_foodentry_createdby'),
    ]

    operations = [
        # Delete all old proposals first
        migrations.RunPython(delete_old_proposals, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='foodproposal',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='caloriesPerServing',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='carbohydrateContent',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='dietaryOptions',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='fatContent',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='micronutrients',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='nutritionScore',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='proteinContent',
        ),
        migrations.RemoveField(
            model_name='foodproposal',
            name='servingSize',
        ),
        migrations.AddField(
            model_name='foodproposal',
            name='food_entry',
            field=models.OneToOneField(blank=True, help_text='The private FoodEntry being proposed for public validation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='foods.foodentry'),
        ),
    ]
