# Generated by Django migration script on 2025-12-13
# Adds allergen tags to all existing food entries based on name keyword matching

from django.db import migrations


# Allergen keyword mappings for inference
ALLERGEN_KEYWORDS = {
    "milk": [
        "milk", "cheese", "yogurt", "dairy", "butter", "cream", "whey",
        "casein", "lactose", "ice cream", "gelato", "ricotta", "mozzarella",
        "parmesan", "cheddar", "brie", "feta", "cottage cheese", "sour cream",
        "half and half", "condensed milk", "evaporated milk", "buttermilk",
        "kefir", "ghee", "custard", "pudding", "alfredo", "queso", "nacho cheese",
        "cream cheese", "swiss", "provolone", "gouda", "gruyere", "monterey",
        "colby", "american cheese", "velveeta", "cheesecake", "latte", "cappuccino",
        "mocha", "creamer", "whipped"
    ],
    "eggs": [
        "egg", "omelet", "omelette", "mayonnaise", "meringue", "quiche",
        "frittata", "scrambled", "poached", "sunny side", "over easy",
        "hard boiled", "soft boiled", "deviled", "hollandaise", "aioli",
        "carbonara", "french toast", "souffle", "eggnog"
    ],
    "peanuts": ["peanut", "groundnut"],
    "tree nuts": [
        "almond", "walnut", "pecan", "cashew", "pistachio", "hazelnut",
        "macadamia", "brazil nut", "chestnut", "pine nut", "praline",
        "marzipan", "nougat", "gianduja", "nutella"
    ],
    "fish": [
        "fish", "salmon", "tuna", "cod", "halibut", "anchovy", "sardine",
        "trout", "tilapia", "bass", "catfish", "flounder", "haddock",
        "herring", "mackerel", "perch", "snapper", "sole", "swordfish",
        "mahi", "pollock", "whiting", "grouper", "pike", "carp", "mullet",
        "roughy", "walleye", "smelt", "roe", "caviar", "surimi"
    ],
    "shellfish": [
        "shrimp", "crab", "lobster", "oyster", "clam", "mussel", "scallop",
        "crawfish", "crayfish", "langostino", "prawn", "calamari", "squid",
        "octopus", "abalone", "conch", "snail", "escargot", "cockle", "whelk"
    ],
    "soy": ["soy", "soya", "tofu", "edamame", "tempeh", "miso", "natto", "soybean", "teriyaki"],
    "wheat": [
        "wheat", "bread", "pasta", "flour", "noodle", "cracker", "biscuit",
        "cookie", "cake", "pastry", "croissant", "bagel", "muffin", "pancake",
        "waffle", "pretzel", "pita", "tortilla", "couscous", "bulgur",
        "farina", "semolina", "seitan", "bun", "roll", "toast", "crouton",
        "stuffing", "breaded", "battered", "dumpling", "pierogi", "ravioli",
        "lasagna", "macaroni", "spaghetti", "fettuccine", "linguine",
        "penne", "pizza", "pie crust", "biscotti", "brownie", "doughnut",
        "donut", "english muffin", "french bread", "sourdough", "focaccia",
        "ciabatta", "brioche", "challah", "naan", "popover", "scone",
        "turnover", "strudel", "phyllo", "wonton", "gyoza"
    ],
    "sesame": ["sesame", "tahini", "halvah", "hummus", "benne"],
    "gluten": [
        "wheat", "barley", "rye", "malt", "triticale", "spelt", "farro",
        "kamut", "einkorn", "durum", "semolina", "couscous", "bulgur",
        "seitan", "bread", "pasta", "flour", "beer", "ale", "lager",
        "stout", "porter"
    ],
}


def infer_allergens(description):
    """Infer allergens from food description using keyword matching."""
    allergens = []
    description_lower = description.lower()
    for allergen_name, keywords in ALLERGEN_KEYWORDS.items():
        if any(keyword in description_lower for keyword in keywords):
            allergens.append(allergen_name)
    return allergens


def add_allergen_tags(apps, schema_editor):
    """Add allergen tags to all existing food entries."""
    FoodEntry = apps.get_model("foods", "FoodEntry")
    Allergen = apps.get_model("foods", "Allergen")

    # Create all allergen entries if they don't exist
    allergen_objects = {}
    for name in ALLERGEN_KEYWORDS.keys():
        allergen, _ = Allergen.objects.get_or_create(name=name)
        allergen_objects[name] = allergen

    print(f"✓ Created/verified {len(allergen_objects)} allergen types")

    # Process all foods
    total_foods = FoodEntry.objects.count()
    foods_updated = 0
    allergens_assigned = 0

    print(f"Processing {total_foods} foods...")

    for food in FoodEntry.objects.all().iterator():
        inferred = infer_allergens(food.name)
        if inferred:
            allergen_objs = [allergen_objects[name] for name in inferred]
            food.allergens.set(allergen_objs)
            foods_updated += 1
            allergens_assigned += len(allergen_objs)

    print(f"✓ Updated {foods_updated} foods with {allergens_assigned} allergen tags")


def reverse_migration(apps, schema_editor):
    """Remove allergen tags from all food entries."""
    FoodEntry = apps.get_model("foods", "FoodEntry")
    for food in FoodEntry.objects.all().iterator():
        food.allergens.clear()
    print("✓ Removed all allergen tags from foods")


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0022_refactor_food_proposal"),
    ]

    operations = [
        migrations.RunPython(add_allergen_tags, reverse_migration),
    ]
