# Generated by Django 5.2.8 on 2025-12-14 20:03

from django.db import migrations


def normalize_to_100g(apps, schema_editor):
    """
    Normalize all nutrient values (protein, fat, carbohydrate, calories) to per 100g.
    Currently they are stored per servingSize.
    """
    FoodEntry = apps.get_model('foods', 'FoodEntry')

    updated_count = 0
    for food in FoodEntry.objects.all():
        if food.servingSize and food.servingSize > 0:
            # Calculate normalization factor
            factor = 100.0 / food.servingSize

            # Normalize and round macronutrients
            food.proteinContent = round(food.proteinContent * factor, 2)
            food.fatContent = round(food.fatContent * factor, 2)
            food.carbohydrateContent = round(food.carbohydrateContent * factor, 2)

            # Normalize and round calories
            food.caloriesPerServing = round(food.caloriesPerServing * factor, 2)

            food.save()
            updated_count += 1

    print(f"Normalized {updated_count} food entries to per 100g values")


def denormalize_from_100g(apps, schema_editor):
    """
    Reverse operation: convert from per 100g back to per servingSize.
    This is the reverse of normalize_to_100g.
    """
    FoodEntry = apps.get_model('foods', 'FoodEntry')

    updated_count = 0
    for food in FoodEntry.objects.all():
        if food.servingSize and food.servingSize > 0:
            # Calculate denormalization factor
            factor = food.servingSize / 100.0

            # Denormalize and round macronutrients
            food.proteinContent = round(food.proteinContent * factor, 2)
            food.fatContent = round(food.fatContent * factor, 2)
            food.carbohydrateContent = round(food.carbohydrateContent * factor, 2)

            # Denormalize and round calories
            food.caloriesPerServing = round(food.caloriesPerServing * factor, 2)

            food.save()
            updated_count += 1

    print(f"Denormalized {updated_count} food entries back to per serving size values")


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0025_alter_foodproposal_proposedby'),
    ]

    operations = [
        migrations.RunPython(normalize_to_100g, reverse_code=denormalize_from_100g),
    ]
