import React, { useState } from 'react';
import {Food} from '../../lib/apiClient';
import FoodDetail from '../foods/FoodDetail';

interface weeklyMealPlan {
    [key: string]: [Food, Food, Food]; // Change to allow string keys
}


// Mock Data Generated by ChatGPT, to be used until backend integration is done
let Pork: Food = {
  id: 101,
  name: "Pork Tenderloin",
  category: "Meat",
  servingSize: 100, // g
  caloriesPerServing: 143,
  proteinContent: 26,     // g
  fatContent: 4,          // g
  carbohydrateContent: 0, // g
  allergens: [],
  dietaryOptions: ["gluten-free", "keto-friendly", "high-protein"],
  nutritionScore: 62,
  imageUrl: "https://example.com/images/pork-tenderloin.png"
};
let Falafel: Food = {
  id: 102,
  name: "Falafel",
  category: "Legume/Plant-based",
  servingSize: 100, // g
  caloriesPerServing: 333,
  proteinContent: 13,  // g
  fatContent: 17,      // g
  carbohydrateContent: 31, // g
  allergens: ["sesame"], // often includes tahini; may contain gluten depending on recipe
  dietaryOptions: ["vegetarian", "vegan", "dairy-free", "high-fiber"],
  nutritionScore: 74,
  imageUrl: "https://example.com/images/falafel.png"
};
let Chicken: Food = {
  id: 103,
  name: "Chicken Breast",
  category: "Poultry",
  servingSize: 100, // g
  caloriesPerServing: 165,
  proteinContent: 31,     // g
  fatContent: 3.6,        // g
  carbohydrateContent: 0, // g
  allergens: [],
  dietaryOptions: ["gluten-free", "keto-friendly", "high-protein"],
  nutritionScore: 78,
  imageUrl: "https://example.com/images/chicken-breast.png"
};


let MealPlans : { [key:string] : weeklyMealPlan} = {
    'halal' : {monday: [Falafel, Chicken, Falafel], tuesday: [Chicken, Falafel, Chicken], wednesday: [Falafel, Chicken, Falafel], thursday: [Chicken, Falafel, Chicken], friday: [Falafel, Chicken, Falafel], saturday: [Chicken, Falafel, Chicken], sunday: [Falafel, Chicken, Falafel]},
    'vegan' : {monday: [Falafel, Falafel, Falafel], tuesday: [Falafel, Falafel, Falafel], wednesday: [Falafel, Falafel, Falafel], thursday: [Falafel, Falafel, Falafel], friday: [Falafel, Falafel, Falafel], saturday: [Falafel, Falafel, Falafel], sunday: [Falafel, Falafel, Falafel]},
    'high-protein' : {monday: [Chicken, Pork, Chicken], tuesday: [Pork, Chicken, Pork], wednesday: [Chicken, Pork, Chicken], thursday: [Pork, Chicken, Pork], friday: [Chicken, Pork, Chicken], saturday: [Pork, Chicken, Pork], sunday: [Chicken, Pork, Chicken]},
}


const MealPlanner = () => {
    const [dietaryPreference, setDietaryPreference] = useState('high-protein');
    const [selectedFood, setSelectedFood] = useState<Food | null>(null);

    const handleDietaryPreferenceChange = (event: { target: { value: React.SetStateAction<string>; }; }) => {
        setDietaryPreference(event.target.value);
    };

    const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
    const meals = ['Breakfast', 'Lunch', 'Dinner'];

    return (
        <div className="w-full py-12">
            <div className="nh-container">
                <div className="mb-8 flex flex-col items-center">
                    <h1 className="nh-title text-center">Create Your Meal Plan</h1>
                    <p className="nh-text text-lg max-w-2xl text-center">
                        Choose your time period and dietary preferences to start your nutritious journey.
                    </p>
                </div>

                <div className="flex flex-col md:flex-row gap-8">
                    <div className="w-full md:w-2/3">
                        <div className="space-y-4">
                            {days.map(day => (
                                <div key={day} className="nh-card">
                                    <h3 className="text-lg font-semibold text-gray-900 mb-4">{day}</h3>
                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                        {meals.map((meal,i) => (
                                            <div 
                                                key={`${day}-${meal}`} 
                                                className="bg-gray-50 rounded-md p-4 border border-gray-100 cursor-pointer hover:shadow-md transition-shadow"
                                                onClick={() => setSelectedFood(MealPlans[dietaryPreference][day.toLowerCase() as keyof weeklyMealPlan][i])}
                                            >
                                                <div className="text-sm font-medium text-gray-500 mb-2">{meal}</div>
                                                <div className="text-sm text-gray-900">
                                                    {MealPlans[dietaryPreference][day.toLowerCase() as keyof weeklyMealPlan][i].name}
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="w-full md:w-1/3">
                        <div className="sticky top-20">
                            <img 
                                src="/assets/gpt_food_calendar.png" 
                                alt="Meal Planning" 
                                className="w-full max-w-xs mx-auto rounded-lg shadow-sm" 
                            />
                            <div className="nh-card mb-6">
                                <div className="space-y-6">
                                    <div className="flex flex-col space-y-2">
                                        <label className="text-sm font-medium text-gray-700">Plan Duration</label>
                                        <select className="form-select block w-full px-4 py-2 text-sm border-gray-300 rounded-md bg-gray-50 focus:ring-primary focus:border-primary">
                                            <option>Weekly</option>
                                            <option>Daily</option>
                                        </select>
                                    </div>
                                    
                                    <div className="flex flex-col space-y-2">
                                        <label className="text-sm font-medium text-gray-700">Dietary Preference</label>
                                        <select 
                                            value={dietaryPreference}
                                            onChange={handleDietaryPreferenceChange}
                                            className="form-select block w-full px-4 py-2 text-sm border-gray-300 rounded-md bg-gray-50 focus:ring-primary focus:border-primary"
                                        >
                                            <option value="high-protein">High-protein</option>
                                            <option value="halal">Halal</option>
                                            <option value="vegan">Vegan</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            
                            <div className="nh-card">
                                <h3 className="nh-subtitle mb-3 text-sm">Planning Tips</h3>
                                <ul className="nh-text text-xs space-y-2">
                                    <li>• Consider your daily calorie needs</li>
                                    <li>• Include a variety of food groups</li>
                                    <li>• Plan for leftovers</li>
                                    <li>• Check your available cooking time</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <FoodDetail 
                    food={selectedFood}
                    open={!!selectedFood}
                    onClose={() => setSelectedFood(null)}
                />
            </div>
        </div>
    );
};

export default MealPlanner;

