import {Food} from '../../lib/apiClient';

// Mock Data Generated by ChatGPT, to be used until backend integration is done

let Salmon: Food = {
  id: 104,
  name: "Grilled Salmon",
  category: "Seafood",
  servingSize: 100,
  caloriesPerServing: 208,
  proteinContent: 20,
  fatContent: 13,
  carbohydrateContent: 0,
  allergens: ["fish"],
  dietaryOptions: ["gluten-free", "keto-friendly", "pescatarian"],
  nutritionScore: 85,
  imageUrl: ""
};

let Tofu: Food = {
  id: 105,
  name: "Firm Tofu",
  category: "Plant Protein",
  servingSize: 100,
  caloriesPerServing: 76,
  proteinContent: 8,
  fatContent: 4.8,
  carbohydrateContent: 1.9,
  allergens: ["soy"],
  dietaryOptions: ["vegan", "vegetarian", "gluten-free"],
  nutritionScore: 79,
  imageUrl: ""
};

let BeefSteak: Food = {
  id: 106,
  name: "Beef Sirloin Steak",
  category: "Meat",
  servingSize: 100,
  caloriesPerServing: 250,
  proteinContent: 26,
  fatContent: 17,
  carbohydrateContent: 0,
  allergens: [],
  dietaryOptions: ["gluten-free", "keto-friendly", "high-protein"],
  nutritionScore: 70,
  imageUrl: ""
};

let Shrimp: Food = {
  id: 107,
  name: "Boiled Shrimp",
  category: "Seafood",
  servingSize: 100,
  caloriesPerServing: 99,
  proteinContent: 24,
  fatContent: 0.3,
  carbohydrateContent: 0.2,
  allergens: ["shellfish"],
  dietaryOptions: ["pescatarian", "gluten-free", "low-fat"],
  nutritionScore: 83,
  imageUrl: ""
};

let Quinoa: Food = {
  id: 108,
  name: "Cooked Quinoa",
  category: "Grain",
  servingSize: 100,
  caloriesPerServing: 120,
  proteinContent: 4.1,
  fatContent: 1.9,
  carbohydrateContent: 21,
  allergens: [],
  dietaryOptions: ["vegan", "gluten-free", "high-fiber"],
  nutritionScore: 80,
  imageUrl: ""
};

let LentilSoup: Food = {
  id: 109,
  name: "Lentil Soup",
  category: "Legume/Plant-based",
  servingSize: 250,
  caloriesPerServing: 186,
  proteinContent: 12,
  fatContent: 3.6,
  carbohydrateContent: 27,
  allergens: [],
  dietaryOptions: ["vegan", "high-fiber", "low-fat"],
  nutritionScore: 77,
  imageUrl: ""
};

let GreekYogurt: Food = {
  id: 110,
  name: "Greek Yogurt (Plain, Nonfat)",
  category: "Dairy",
  servingSize: 100,
  caloriesPerServing: 59,
  proteinContent: 10,
  fatContent: 0.4,
  carbohydrateContent: 3.6,
  allergens: ["milk"],
  dietaryOptions: ["vegetarian", "high-protein"],
  nutritionScore: 84,
  imageUrl: ""
};

let BrownRice: Food = {
  id: 111,
  name: "Cooked Brown Rice",
  category: "Grain",
  servingSize: 100,
  caloriesPerServing: 111,
  proteinContent: 2.6,
  fatContent: 0.9,
  carbohydrateContent: 23,
  allergens: [],
  dietaryOptions: ["vegan", "gluten-free"],
  nutritionScore: 72,
  imageUrl: ""
};

let Avocado: Food = {
  id: 112,
  name: "Avocado",
  category: "Fruit",
  servingSize: 100,
  caloriesPerServing: 160,
  proteinContent: 2,
  fatContent: 15,
  carbohydrateContent: 9,
  allergens: [],
  dietaryOptions: ["vegan", "keto-friendly", "high-fiber"],
  nutritionScore: 88,
  imageUrl: ""
};

let Spinach: Food = {
  id: 113,
  name: "Cooked Spinach",
  category: "Vegetable",
  servingSize: 100,
  caloriesPerServing: 23,
  proteinContent: 3,
  fatContent: 0.3,
  carbohydrateContent: 3.8,
  allergens: [],
  dietaryOptions: ["vegan", "low-calorie", "high-iron"],
  nutritionScore: 90,
  imageUrl: ""
};

let Almonds: Food = {
  id: 114,
  name: "Raw Almonds",
  category: "Nut",
  servingSize: 28,
  caloriesPerServing: 164,
  proteinContent: 6,
  fatContent: 14,
  carbohydrateContent: 6,
  allergens: ["tree nuts"],
  dietaryOptions: ["vegan", "keto-friendly"],
  nutritionScore: 76,
  imageUrl: ""
};

let Egg: Food = {
  id: 115,
  name: "Boiled Egg",
  category: "Poultry",
  servingSize: 50,
  caloriesPerServing: 78,
  proteinContent: 6.3,
  fatContent: 5.3,
  carbohydrateContent: 0.6,
  allergens: ["egg"],
  dietaryOptions: ["keto-friendly", "high-protein"],
  nutritionScore: 80,
  imageUrl: ""
};

let Apple: Food = {
  id: 116,
  name: "Apple",
  category: "Fruit",
  servingSize: 182,
  caloriesPerServing: 95,
  proteinContent: 0.5,
  fatContent: 0.3,
  carbohydrateContent: 25,
  allergens: [],
  dietaryOptions: ["vegan", "gluten-free"],
  nutritionScore: 85,
  imageUrl: ""
};

let Oatmeal: Food = {
  id: 117,
  name: "Cooked Oatmeal",
  category: "Grain",
  servingSize: 100,
  caloriesPerServing: 68,
  proteinContent: 2.4,
  fatContent: 1.4,
  carbohydrateContent: 12,
  allergens: ["gluten"],
  dietaryOptions: ["vegetarian", "high-fiber"],
  nutritionScore: 78,
  imageUrl: ""
};

let SweetPotato: Food = {
  id: 118,
  name: "Baked Sweet Potato",
  category: "Vegetable",
  servingSize: 130,
  caloriesPerServing: 112,
  proteinContent: 2,
  fatContent: 0.1,
  carbohydrateContent: 26,
  allergens: [],
  dietaryOptions: ["vegan", "gluten-free"],
  nutritionScore: 87,
  imageUrl: ""
};

let Broccoli: Food = {
  id: 119,
  name: "Steamed Broccoli",
  category: "Vegetable",
  servingSize: 100,
  caloriesPerServing: 35,
  proteinContent: 2.8,
  fatContent: 0.4,
  carbohydrateContent: 7,
  allergens: [],
  dietaryOptions: ["vegan", "low-calorie", "high-fiber"],
  nutritionScore: 92,
  imageUrl: ""
};

let PeanutButter: Food = {
  id: 120,
  name: "Peanut Butter (Natural)",
  category: "Nut Spread",
  servingSize: 32,
  caloriesPerServing: 190,
  proteinContent: 8,
  fatContent: 16,
  carbohydrateContent: 6,
  allergens: ["peanuts"],
  dietaryOptions: ["vegetarian", "keto-friendly"],
  nutritionScore: 70,
  imageUrl: ""
};

let CottageCheese: Food = {
  id: 121,
  name: "Cottage Cheese (Low-fat)",
  category: "Dairy",
  servingSize: 100,
  caloriesPerServing: 81,
  proteinContent: 11,
  fatContent: 2.3,
  carbohydrateContent: 3.4,
  allergens: ["milk"],
  dietaryOptions: ["vegetarian", "high-protein"],
  nutritionScore: 79,
  imageUrl: ""
};

let Hummus: Food = {
  id: 122,
  name: "Hummus",
  category: "Dip/Legume",
  servingSize: 100,
  caloriesPerServing: 166,
  proteinContent: 8,
  fatContent: 10,
  carbohydrateContent: 14,
  allergens: ["sesame"],
  dietaryOptions: ["vegan", "gluten-free"],
  nutritionScore: 75,
  imageUrl: ""
};

let Tuna: Food = {
  id: 123,
  name: "Canned Tuna (in Water)",
  category: "Seafood",
  servingSize: 100,
  caloriesPerServing: 132,
  proteinContent: 28,
  fatContent: 1.3,
  carbohydrateContent: 0,
  allergens: ["fish"],
  dietaryOptions: ["pescatarian", "high-protein"],
  nutritionScore: 81,
  imageUrl: ""
};

let MixedSalad: Food = {
  id: 124,
  name: "Mixed Green Salad",
  category: "Vegetable",
  servingSize: 150,
  caloriesPerServing: 60,
  proteinContent: 2,
  fatContent: 3,
  carbohydrateContent: 7,
  allergens: [],
  dietaryOptions: ["vegan", "low-calorie"],
  nutritionScore: 89,
  imageUrl: ""
};

let Pork: Food = {
  id: 101,
  name: "Pork Tenderloin",
  category: "Meat",
  servingSize: 100, // g
  caloriesPerServing: 143,
  proteinContent: 26,     // g
  fatContent: 4,          // g
  carbohydrateContent: 0, // g
  allergens: [],
  dietaryOptions: ["gluten-free", "keto-friendly", "high-protein"],
  nutritionScore: 62,
  imageUrl: ""
};
let Falafel: Food = {
  id: 102,
  name: "Falafel",
  category: "Legume/Plant-based",
  servingSize: 100, // g
  caloriesPerServing: 333,
  proteinContent: 13,  // g
  fatContent: 17,      // g
  carbohydrateContent: 31, // g
  allergens: ["sesame"], // often includes tahini; may contain gluten depending on recipe
  dietaryOptions: ["vegetarian", "vegan", "dairy-free", "high-fiber"],
  nutritionScore: 74,
  imageUrl: ""
};
let Chicken: Food = {
  id: 103,
  name: "Chicken Breast",
  category: "Poultry",
  servingSize: 100, // g
  caloriesPerServing: 165,
  proteinContent: 31,     // g
  fatContent: 3.6,        // g
  carbohydrateContent: 0, // g
  allergens: [],
  dietaryOptions: ["gluten-free", "keto-friendly", "high-protein"],
  nutritionScore: 78,
  imageUrl: ""
};

let MockFoods: Food[] = [
  Salmon,
  Tofu,
  BeefSteak,
  Shrimp,
  Quinoa,
  LentilSoup,
  GreekYogurt,
  BrownRice,
  Avocado,
  Spinach,
  Almonds,
  Egg,
  Apple,
  Oatmeal,
  SweetPotato,
  Broccoli,
  PeanutButter,
  CottageCheese,
  Hummus,
  Tuna,
  MixedSalad,
  Pork,
  Falafel,
    Chicken
];

export { MockFoods, Falafel, Chicken, Pork };


