# Generated by Django 5.2.1 on 2025-05-10 19:16

from django.db import migrations, models


def create_initial_tags(apps, schema_editor):
    Tag = apps.get_model('forum', 'Tag')
    
    # Create initial tags including dietary tags
    initial_tags = [
        'Dietary tip',
        'Recipe', 
        'Meal plan',
        'vegan',
        'halal',
        'high-protein'
    ]
    
    for tag_name in initial_tags:
        Tag.objects.get_or_create(name=tag_name)


def remove_initial_tags(apps, schema_editor):
    Tag = apps.get_model('forum', 'Tag')
    
    # Remove all initial tags
    initial_tags = [
        'Dietary tip',
        'Recipe',
        'Meal plan', 
        'vegan',
        'halal',
        'high-protein'
    ]
    
    Tag.objects.filter(name__in=initial_tags).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="forum.tag"),
        ),
        migrations.RunPython(create_initial_tags, remove_initial_tags),
    ]
