# Generated by Django 5.2.7 on 2025-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_add_dietary_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="currency",
            field=models.CharField(default="TRY", max_length=3),
        ),
        migrations.AddField(
            model_name="recipe",
            name="price_category",
            field=models.CharField(
                blank=True,
                choices=[("₺", "₺"), ("₺ ₺", "₺ ₺"), ("₺ ₺₺", "₺ ₺₺")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
