# Generated by Django 5.1.3 on 2025-12-13 14:21

from django.db import migrations, models


def populate_custom_amount(apps, schema_editor):
    """
    Set customAmount to the value of amount for existing RecipeIngredient records.
    This is needed because customAmount was just added with a default of 0.
    """
    RecipeIngredient = apps.get_model("forum", "RecipeIngredient")

    # Update all existing records to set customAmount = amount
    for ingredient in RecipeIngredient.objects.all():
        ingredient.customAmount = ingredient.amount
        ingredient.save(update_fields=["customAmount"])


def reverse_populate_custom_amount(apps, schema_editor):
    """
    Reset customAmount to 0 for all RecipeIngredient records.
    """
    RecipeIngredient = apps.get_model("forum", "RecipeIngredient")
    RecipeIngredient.objects.all().update(customAmount=0.0)


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_recipe_currency_recipe_price_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='customUnit',
            field=models.TextField(
                default='g',
                help_text='Traditional unit of measurement (e.g. tablespoon, cup, etc.) this will be used in UI.'
            ),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='customAmount',
            field=models.FloatField(
                default=0.0,
                help_text='Amount in custom unit'
            ),
        ),
        migrations.RunPython(populate_custom_amount, reverse_populate_custom_amount),
    ]
