# Generated by Django 5.2.8 on 2025-12-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='customUnit',
            field=models.TextField(default='serving', help_text='Traditional unit of measurement (e.g. tablespoon, cup, etc.) this will be used in UI.'),
        ),
    ]
