# Generated by Django 5.2.7 on 2025-11-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_planner", "0002_dailynutritionlog_foodlogentry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlogentry",
            name="serving_size",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Serving size multiplier (e.g., 2 for two servings)",
                max_digits=10,
            ),
        ),
    ]
