# Generated by Django 5.2.8 on 2025-11-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_foodproposal_is_private'),
        ('meal_planner', '0003_increase_serving_size_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlogentry',
            name='private_food',
            field=models.ForeignKey(blank=True, help_text='Reference to private food (rejected proposal)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_log_entries', to='foods.foodproposal'),
        ),
        migrations.AlterField(
            model_name='foodlogentry',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='foods.foodentry'),
        ),
    ]
