# Generated by Django 5.2.8 on 2025-12-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0004_foodlogentry_private_food_alter_foodlogentry_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlogentry',
            name='private_food',
        ),
    ]
