# Generated by Django 5.2.8 on 2025-12-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0005_remove_foodlogentry_private_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='micronutrients_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregated micronutrient totals for the meal plan'),
        ),
    ]
