# Generated by Django 5.2.7 on 2025-12-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0025_alter_foodproposal_proposedby"),
        ("meal_planner", "0006_mealplan_micronutrients_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedFoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serving_size",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Serving size multiplier (e.g., 2 for two servings)",
                        max_digits=10,
                    ),
                ),
                (
                    "serving_unit",
                    models.CharField(
                        default="serving",
                        help_text="Unit of measurement (e.g., serving, cup, gram)",
                        max_length=50,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("calories", models.DecimalField(decimal_places=2, max_digits=8)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=7)),
                ("carbohydrates", models.DecimalField(decimal_places=2, max_digits=7)),
                ("fat", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "micronutrients",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Micronutrient values for this serving",
                    ),
                ),
                ("planned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_entries",
                        to="meal_planner.dailynutritionlog",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_log_entries",
                        to="foods.foodentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Planned Food Entries",
                "ordering": ["planned_at"],
            },
        ),
    ]
